name: Publish Android

on:
  push:
    branches: [ main ]

jobs:
  build-and-publish-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'recipe-keystore'
          encodedString: ${{ secrets.KEYSTORE }}

      - name: Bump version
        uses: chkfung/android-version-actions@v1.2.3
        with:
          gradlePath: composeApp/build.gradle.kts
          versionCode: ${{github.run_number}}
          versionName: "1.0"

      - name: Build Android Release
        run: ./gradlew :composeApp:bundleRelease
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

      - name: Publish to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: de.rakhman.cooking
          releaseFiles: 'composeApp/build/outputs/bundle/release/composeApp-release.aab'
          mappingFile: 'composeApp/build/outputs/bundle/release/mapping.txt'
          track: internal
