name: Publish Android

on:
  push:
    branches: [ main ]

jobs:
  build-and-publish-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'recipe-keystore.jks'
          fileDir: ${{ github.workspace }}
          encodedString: ${{ secrets.KEYSTORE }}

      - name: Set versionCode
        run: |
          VERSION_CODE=$((GITHUB_RUN_NUMBER + 10))
          echo "Setting versionCode to $VERSION_CODE"
          sed -i -E "s/versionCode = [0-9]+/versionCode = $VERSION_CODE/" composeApp/build.gradle.kts

      - name: Build Android Release
        run: ./gradlew :composeApp:bundleRelease
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

      - name: Publish to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: de.rakhman.cooking
          releaseFiles: 'composeApp/build/outputs/bundle/release/composeApp-release.aab'
          mappingFile: 'composeApp/build/outputs/mapping/release/mapping.txt'
          track: alpha
