name: Publish Android Debug APK for PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-publish-debug-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Android Debug APK
        run: ./gradlew :composeApp:assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: composeApp/build/outputs/apk/debug/composeApp-debug.apk

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Debug APK for PR

      - name: Create or Update Comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### Debug APK for PR #${{ github.event.pull_request.number }}
            
            A debug APK has been built for this PR.
            
            You can download it from the "Artifacts" section of this workflow run:
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            
            Or directly access it by clicking on the "Summary" link of this workflow run.
          edit-mode: replace
          token: ${{ secrets.GITHUB_TOKEN }}